providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_23", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile", "pnpm prisma:push", "pnpm prisma:generate"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start:prod"
